### ISSUE TITLE
Correct Issues w/ CSV Downloads

### ISSUE THREAD

**Issue by JAMAMIL** [CMSgov/CMCS-DSG-DSS-Certification-Staging#100]
## What is the goal or purpose of this issue?
When a user clicks on the link to download content to a csv file, that file is not generating the content.
The purpose of this issue is to correct the issue(s) preventing the content from properly generating a csv file.

## This issue is resolved when...
- [ ] The download link properly generates content into the csv file
- [ ] The corrections are verified

## Additional context
_Add any other context, screenshots, or links about the request here_
[MES Outcomes - State-Specific Eligibility and Enrollment (1).csv](https://github.com/CMSgov/CMCS-DSG-DSS-Certification-Staging/files/7971958/MES.Outcomes.-.State-Specific.Eligibility.and.Enrollment.1.csv)
[MES Outcomes - CMS-Required Eligibility and Enrollment.csv](https://github.com/CMSgov/CMCS-DSG-DSS-Certification-Staging/files/7971959/MES.Outcomes.-.CMS-Required.Eligibility.and.Enrollment.csv)

**Comment by nickarrow** [comment]
This is a duplicate of #102 closing.
