### ISSUE TITLE
MVP Visual style updates 

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Certification-Staging#17]
## What is the goal or purpose of this issue?
Update the styles on the Github Pages site - work is currently happening in the read-the-docs branch. 

## This issue is resolved when...
- [x] Update .ds-h1 to `font-size: 48px` and `font-weight: 700` or `font-weight: bold`
- [x] Remove  `margin-left` from .ds-l-container
- [x] Update .content `padding-left: 2rem' 
- [x] Remove the CMS logo from the side nav
- [x] Add a header component with just the project name "MES Certification Repository" - no search bar or links. 
- [x] Can we add a slim footer w/ the CMS logo + Name and the copy "This site is maintained by the CMCS Data and Systems Group." 

## Additional context

I'm mainly trying to get a little closer to the cms design system

We may need to adjust the container or content margins after adding the header/footer

**Comment by nickarrow** [comment]
I pointed our pages build to the 17-visual-styles branch, so you can see it rendering here if this helps in anyway: https://cmsgov.github.io/CMCS-DSG-DSS-Certification/

**Comment by amyashida** [comment]
@NAretakis I merged the updates to the `read-the-docs` branch - any chance we could point it back to that one?

**Comment by nickarrow** [comment]
pointed back to read-the-docs

**Comment by nickarrow** [comment]
https://cmsgov.github.io/CMCS-DSG-DSS-Certification/
