### ISSUE TITLE
Plan post MVP User-Testing

### ISSUE THREAD

**Issue by nickarrow** [CMSgov/CMCS-DSG-DSS-Certification-Staging#28]
## What is the goal or purpose of this issue?
Conduct another round of user testing with CMS, Vendors, and State staff to identify improvements that can be made to the site post MVP. 

## This issue is resolved when...
- [x] A research plan is written
- [x] Participants have been recruited + scheduled 
- [x] Interview guide has been drafted

## Additional context
_Add any other context, screenshots, or links about the request here_

**Comment by amyashida** [comment]
Potential things to ask: 
- Future feature development - How would you like to interact with this? Have a more robust back and forth? 
- What other content would you like here? 
- How would you like to be notified about changes/updates?

**Comment by nickarrow** [comment]
Closing this issue. We have SOs and states lined up. And working with two vendors.
