### ISSUE TITLE
Update pages to use CSV linked tables/data

### ISSUE THREAD

**Issue by nickarrow** [CMSgov/CMCS-DSG-DSS-Certification-Staging#29]
## What is the goal or purpose of this issue?
The purpose of this issue is to research and implement a process to link CSV data to the tables presented on each business area page. This way the downloadable CSV is always aligned with the information presented on each page. 

## This issue is resolved when...
- [ ] A database or centrally stored spreadsheet is the single source of Outcomes and Metrics information. Each outcomes table across the site pulls data from the database/spreadsheet. 
- [ ] Edits and additions to the outcomes can be added via the central database/spreadsheet

## Additional context
_Add any other context, screenshots, or links about the request here_

**Comment by amyashida** [comment]
Here is the [demo for the csv](https://github.com/CMSgov/CMCS-DSG-DSS-Certification/blob/main/csv-demo.md)
