### ISSUE TITLE
Update side-nav to collapse MES business areas

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Certification-Staging#35]

**Comment by amyashida** [comment]
What is the goal or purpose of this issue?

- As a user, I want to see the whole side nav and expand the MES business areas, so I can understand what all of my navigation options are

This issue is resolved when...
- The MES business area section of the side nave can expand and collapse when clicked on

**Comment by mgwalker** [comment]
Should the MES BA section start collapsed or expanded?
