### ISSUE TITLE
Update presentation

### ISSUE THREAD

**Issue by pkroft** [CMSgov/CMCS-DSG-DSS-Certification-Staging#49]
## What is the goal or purpose of this issue?
Update the presentation to reflect the latest version of the repo

## This issue is resolved when...
- [x] Screenshots in the repo have been updated to show the latest designs and content
- [x] Text in the presentation aligns with the latest content in the repo

## Additional context
_Add any other context, screenshots, or links about the request here_

**Comment by nickarrow** [comment]
Presentation shared with MeT for presenting!
