### ISSUE TITLE
Minor Edits

### ISSUE THREAD

**Issue by JAMAMIL** [CMSgov/CMCS-DSG-DSS-Certification-Staging#61]
## What is the goal or purpose of this issue?
Purpose of this issue is to update the TPL page to remove markdown design language from the table. Also, assess whether or not the PDMP business area should reflect seven outcomes...six are currently presented.

## This issue is resolved when...
- [x] Markdown design language is removed from the table on the TPL Business Area page.
- [x] The seventh PDMP outcome is added if it is determined that it was inadvertently omitted.
- [x] CMS verifies the changes have been made correctly.

## Additional context
none

**Comment by nickarrow** [comment]
I fixed the markdown language via a merged PR, so I think that one is already done.

**Comment by nickarrow** [comment]
MITRE confirmed that for PDMP #7, we they re-reviewed the PDMP outcomes and it is their recommendation that we actually get rid of the 7th one, as they don't know of any PDMP systems that have this functionality. Additionally, it is not in the regs or the FAQs, so we don't have a regulatory citation for #7. 

@JAMAMIL are you OK with closing this issue per the above? We can always re-open if we need to add it back for some reason.

**Comment by JAMAMIL** [comment]
Sounds good to me @NAretakis .
