### ISSUE TITLE
Expand Google Analytics to see which pages users are viewing

### ISSUE THREAD

**Issue by nickarrow** [CMSgov/CMCS-DSG-DSS-Certification-Staging#70]
## What is the goal or purpose of this issue?
The purpose of this issue is to expand or enhance the Google Analytics code snippet so that we can get some more detailed analytics. Currently we get basic stats such as how many people are currently on the site (see screenshot below). But what we would like to see is information on the sub pages. 

If we could know which pages users are navigating to within the site, and which pages are most frequently visited, that would help us focus research and development. Open to any ideas on how to expand the analytics reporting futher.

## This issue is resolved when...
1. Google analytics is expanded so that we can see which pages a user is accessing and page counts
2. Any other low LOE analytics expansion is added.

## Additional context
![image](https://user-images.githubusercontent.com/34281281/137151401-438f957e-af2e-4f20-a3a0-60a280bf4389.png)

**This is all we get "Pages and Screens"**
![image](https://user-images.githubusercontent.com/34281281/137151538-be73918e-3812-4b26-ac6e-2d2e14d62ed9.png)

**Comment by nickarrow** [comment]
@mgwalker Hiya Greg - do you have any bandwidth to do a bit of research or dev work on this? We have the very basics of analytics, and want to expand it just a little bit further.

**Comment by mgwalker** [comment]
Is there an option in Google Analytics to view stats by page URL instead of by title? That would be an instant fix, but barring that, I'll look into how we can set the title based on which page is currently loaded (which is probably a good idea anyway!).

**Comment by nickarrow** [comment]
I'll have to click around and see if "By URL" is an option. After your PR, I am seeing the "Introduction" page title displayed woot woot
![image](https://user-images.githubusercontent.com/34281281/137382147-c8ace6af-71a4-4d34-85e3-166632bbde7c.png)

**Comment by nickarrow** [comment]
I wonder if the problem is that I put the google analytics code snippet in the `index.md` file. Wondering if there is a better place to locate it so that it permeates all the site pages.

**Comment by mgwalker** [comment]
Oh! D'oh. Yes, that is almost certainly it. I didn't even look. 😬  That can go in `_layouts/default.html` instead and it'll get built into every page.

**Comment by mgwalker** [comment]
Ugh, I should probably not keep linking the issue to the pull request on this one. 😬

**Comment by nickarrow** [comment]
that did it! It's working like a dream! ALL THE DATA! Thanks Greg.
