### ISSUE TITLE
Missing Certification Info

### ISSUE THREAD

**Issue by JAMAMIL** [CMSgov/CMCS-DSG-DSS-Certification-Staging#80]
## Consider adding additional information pertaining to certification
One state inquired on whether or not the artifacts were still required since they weren't a part of the Repo. To have all certification related SMC material in one place and to avoid unintentionally misleading states, we should consider adding missing information from the appendices A-D.

## This issue is resolved when...
- [ ] Consideration has been given to potentially adding information from Appendices A-D that is missing
- [ ] If the decision is made to add the missing info, decide an approach for presenting that info (e.g. separate downloadable files, web page, etc.)
- [ ] Add missing info as determined
- [ ] Review content before finalizing

## Additional context
N/A

**Comment by nickarrow** [comment]
We have broken this issue into a bunch of sub-issues #103 #105 #107 

Closing this issue in favor of those.
