### ISSUE TITLE
Make updates for the UX improvements to the nav

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Certification-Staging#82]
## What is the goal or purpose of this issue?
Update navigation to utilize consistent color and active state across links - right now the drop down menu is always active no matter if you are on it or not

The expected behavior is that the current page correlates with the active state in the navigation so users know where they are on the site. 

Also - the site logo doesn’t operate as a link to the homepage, common in most sites as an emergency exit when people get lost or confused.

The expected behavior is that the logo brings you back to the intro page

## This issue is resolved when...
- [x] the nav has expected and consistent active states
- [x] clicking on the logo brings you back to the intro page

## Additional context
_Add any other context, screenshots, or links about the request here_

**Comment by sknep** [comment]
@amyashida At your convenience, list any other UX/visual changes/etc and I'll get to them shortly!

**Comment by amyashida** [comment]
updated!

**Comment by amyashida** [comment]
@NAretakis i think this got shipped if we want to close it!

**Comment by nickarrow** [comment]
These are done, will be resolved with the latest bugfix and UI pull request. Yay!
