### ISSUE TITLE
Clean up copy edits from UX audit

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Certification-Staging#84]
## What is the goal or purpose of this issue?
The [UX Audit](https://app.box.com/file/885073585075?s=fo8m19j4ckdzo9x125dxnbyg90qse7yu) is in box.

There are a few typos across many pages

change:

- "When state-specific outcomes" to "When _drafting_ state specific outcomes" 

- remove the "a" in "to that a specific system" 
- remove the first "continue to" from "which must continue to continue to"

## This issue is resolved when...
- [x] we have fixed the typos in the audit
- [ ] ...

## Additional context
_Add any other context, screenshots, or links about the request here_

**Comment by amyashida** [comment]
@NAretakis i think this got shipped if we want to close it!

**Comment by nickarrow** [comment]
Closing out!
