### ISSUE TITLE
Update H1s on home, outcome, and writing pages to match nav

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Certification-Staging#93]
## What is the goal or purpose of this issue?
The main text on the pages does not match the nav so users may feel confused if they are on the page they clicked on. 

On the home page - remove  "introduction" 

On the outcomes + process and writing page update H1 to match nav

## This issue is resolved when...
- [x] the H1 on the pages matches the above

## Additional context
_Add any other context, screenshots, or links about the request here_

**Comment by amyashida** [comment]
This needs two fixes - I updated the copy in the [page-header-fixes](https://github.com/CMSgov/CMCS-DSG-DSS-Certification-Staging/tree/page-header-fixes) branch, but it looks like the default page layout is duplicating the H1 at the top of the page so it shows up twice. The expected behavior would be to have the H1 text at the top of a page only show up once and it should be as the largest header at the top of the page. 

Going to tag in @sknep to help! 


![image](https://user-images.githubusercontent.com/12942515/145275621-81bd0da8-c3ec-4c4d-b846-80458265ef91.png)

**Comment by sknep** [comment]
Yep, this is using a special jekyll plugin to automatically set a page title _whenever the first line of a markdown file starts with `#` (an h1)_. There's a setting to strip the duplicate title: https://github.com/benbalter/jekyll-titles-from-headings#stripping-titles

Which I've made in the open branch at https://github.com/CMSgov/CMCS-DSG-DSS-Certification-Staging/tree/page-header-fixes. PR incoming!
